### ISSUE TITLE
Реализация мультиаккаунтовости бота

### ISSUE THREAD

**Issue by HoloPaladin** [shtrih/discord-xmpp-transport-bot#1]
Необходимо реализовать функционал, позволяющий боту полноценно "клонировать" пользователей jabber'а в дискорд и наоборот, заводя для каждого пользователя одной из этих систем аккаунт с идентичным ником в другой системе. 
В рамках данного функционала необходимо:
- Формировать первоначальные списки участников конференций в системах для получения списка ников для необходимых к подключению аккаунтов.
- Мониторить системные сообщения на предмет выхода\входа\смены ника пользователей системы для реализации аналогичных изменений во второй системе.
- Предусмотреть возможность существования в системах двух пользователей с одним ником, "клона"  в этом случае снабжать препиской указывающей на то, в какой системе сидит клонируемый пользователь.

**Comment by shtrih** [comment]
Невозможно реализовать.

**Comment by shtrih** [comment]
Реализовано частично: используются никнеймы из джаббера на стороне дискорда с помощью веб-хуков.
