### ISSUE TITLE
TypeError: cannot read property 'bosh' of undefined

### ISSUE THREAD

**Issue by legop3** [shtrih/discord-xmpp-transport-bot#13]
im not sure if this is my problem, the software's problem, or the sevrer's problem, but the only way i could get my bot to log into the jabber server was with no password. every time i tried entering the (correct) password into the config file, it said xmpp authentication error in dms. i dont know if this is related at all to the error im getting now, but the bot seems to work fine until it crashes. 
![image](https://user-images.githubusercontent.com/46182676/78974127-57f21500-7adf-11ea-9d05-cf8531afc1a0.png)
here is a screenshot of when i ran app.js in a windows 7 command prompt
(windows 7 probably isnt ideal for running this, but my server pc already has it, and i have software that only works on windows.)

**Comment by shtrih** [comment]
@legop3 Try patched version. You can close the issue if the error does not repeat

**Comment by legop3** [comment]
i replaced line 216 with the green one, and it still crashed but with a different error. here is a screenshot of the entire thing, from when i run it to when it crashes. it still logged in to all 4 chat rooms without a password in the config file, and it still worked fine until it crashed.
![image](https://user-images.githubusercontent.com/46182676/79017918-7f2cfe80-7b40-11ea-9d9e-b09fa40d26f1.png)

**Comment by shtrih** [comment]
Can you rerun app with debug environment variable? 
You can do it like saving `run.bat`:
```
set DEBUG=*
start node ./app.js
```
And send me new screenshot.

**Comment by legop3** [comment]
run.bat: 
![image](https://user-images.githubusercontent.com/46182676/79018744-8c4aed00-7b42-11ea-9699-0b63e46fee85.png)
i ended up not running it through run.bat, it opened nodejs in a new console window that closed when it crashed.
i ran 'set DEBUG=*', and then app.js

![image](https://user-images.githubusercontent.com/46182676/79020746-adfaa300-7b47-11ea-82d6-707051d102c9.png)
this is the last bit of logging it did until it looks like it just disconnected instead of crashing with an error. it also DMed me with '[Jabber error] XMPP authentication failure'

**Comment by legop3** [comment]
![image](https://user-images.githubusercontent.com/46182676/79021380-56f5cd80-7b49-11ea-8481-58b4b9ed94b6.png)
this time it crashed

**Comment by legop3** [comment]
it lasted signifigantly longer, but 
![image](https://user-images.githubusercontent.com/46182676/79027319-c4115f00-7b59-11ea-9490-7a4b0b5ad0f0.png)

**Comment by legop3** [comment]
so it doesnt seem to be crashing anymore, but it disconnects frequently, with either an authentication error or a socket hang up: 
![image](https://user-images.githubusercontent.com/46182676/79054505-4f026000-7c13-11ea-83b4-68af7391f642.png)

is there any way to get it to reconnect after an authentication error? or anything i could do to make it more stable? i dont think its the server, because i have a client on my phone that is always connected and works fine.

**Comment by legop3** [comment]
also this: 
![image](https://user-images.githubusercontent.com/46182676/79054888-b837a280-7c16-11ea-99d6-21e59e4d9f2d.png)

**Comment by shtrih** [comment]
It seems to be stable after all the fixes.

**Comment by shtrih** [comment]
>i replaced line 216 with the green one

You should redownload whole sources because not all edits are mentioned in this issue. Or execute `git pull origin master` if you use git. Manually making changes, you may accidentally skip some code fixes... Anyway you can check what changes have been made like this: https://github.com/shtrih/discord-xmpp-transport-bot/compare/820e2f5...master

**Comment by legop3** [comment]
i re-downloaded the source, copied over my config file, and everything worked perfectly! thanks so much for the help!
