### ISSUE TITLE
Хайлайты в дискорде

### ISSUE THREAD

**Issue by shtrih** [shtrih/discord-xmpp-transport-bot#2]
Сейчас, если в джаббере написать `@никнейм`, то в дискорде этот никнейм никак не хайлайтится. 
Перед созданием сообщения в дискорде, нужно сопоставить этот никнейм с никами юзеров в дискорде, затем произвести замену текста `@никнейм` на `<@!userID>` согласно [док-ции](https://discordapp.com/developers/docs/resources/channel#message-formatting).

**Comment by HoloPaladin** [comment]
Для полноценной реализации хайлайтов лучше использоваь регулярки. В жабире по-умолчанию @ не ставится. Для выделения ника обращения вроде подходит вот такая регурялка:
`^[@](.*):.*`
это пригодится и будет работать и потом, если будет сделана мультиаккаунтовость
