### ISSUE TITLE
Can't Send Message

### ISSUE THREAD

**Issue by martin3754** [shtrih/discord-xmpp-transport-bot#5]
Bot connects to Discord and XMPP, shows as online. When I type anything into the Discord channel to be sent to XMPP, I get the following:

/home/redacted/discord-xmpp-transport-bot/lib/RemDiscord.js:49
        throw {'error': 'Can\'t send message', channel, message};
        ^
[object Object]

When I use the !send command via DM, it is able to send to the Discord channel. I'm not sure why it's trying to send to Discord when the expected behavior would be to send to the XMPP room.

Please let me know if I can provide any additional information. Thank you!

Best Regards,
Martin

**Comment by shtrih** [comment]
Tried to reproduce and failed. But I fixed the code a bit. Please try again, if the error occurs, check `!ping` command is work?
